### ISSUE TITLE
element as HTMLInputElement

### ISSUE THREAD

**Issue by hold-baby** [momoko8443/how_to_write_a_mvvm_library#1]
element as HTMLInputElement 这个as是什么函数 没有搜索到

**Comment by momoko8443** [comment]
as是typescript的语法，可以把基类指定成具体的子类

**Comment by hold-baby** [comment]
那js如何实现as的方法呢？

**Comment by momoko8443** [comment]
@hold-baby js不需要用as转类型的，因为ts有参数类型强制检测，所以要用as转一下。所以你直接传入参数就行了，不用as

**Comment by hold-baby** [comment]
所噶
